config/routes.rb
Rails.application.routes.draw do
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  get 'sitemap', to: redirect('http://s3-ap-northeast-1.amazonaws.com/'+ENV['S3_BUCKET']+'/sitemaps/sitemap.xml.gz')

  get 'plans/update'

  get 'images/ogp.png', to: 'images#ogp', as: 'images_ogp'

  get 'sessions/new'

  root 'static_pages#home'

  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/rule', to: 'static_pages#rule'
  get  '/privacy', to: 'static_pages#privacy'
  get  '/create', to: 'static_pages#create'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/search', to: 'users#search'
  get '/planup', to: 'plans#new'
  post '/planup', to: 'plans#create'
  get '/clone', to: 'plans#clone'
  post '/clone', to: 'plans#create'
  get '/anonymous_user_planup', to: 'anonymous_user_plans#new'
  post '/anonymous_user_planup', to: 'anonymous_user_plans#create'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :plans, only: [:index, :update, :show, :edit, :new, :create]
  resources :anonymous_user_plans
  resources :users do
    member do
      get :liking
    end
  end
  resources :plans do
    member do
      get :likers
    end
  end
  resources :likes, only: [:create, :destroy]
end

app/models/anonymous_user_plan.rb
class AnonymousUserPlan < ApplicationRecord
  has_many :destinations, as: :placeable, dependent: :destroy, inverse_of: :placeable
  accepts_nested_attributes_for :destinations, allow_destroy: true
  validates :title, presence: true
  validate  :picture_size
  mount_uploader :picture, PictureUploader
  default_scope -> { order(created_at: :desc) }
  amoeba do
    enable
  end

  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/anonymous_user_plans_controller.rb
class AnonymousUserPlansController < ApplicationController
  def show
    @anonymous_user_plan = AnonymousUserPlan.find(params[:id])
    @destinations = @anonymous_user_plan.destinations.order(id:"ASC")
    gon.planData = @destinations.map{|d| d.name}
  end

  def new
    @anonymous_user_plan = AnonymousUserPlan.new
    10.times { @anonymous_user_plan.destinations.build }
  end

  def create
    @anonymous_user_plan = AnonymousUserPlan.new(plan_params)
    if @anonymous_user_plan.save
      redirect_to controller: 'anonymous_user_plans', action: 'show', id: @anonymous_user_plan.id
    else
      flash[:danger] = "タイトルを入力してください"
      redirect_to acition: 'new'
    end
  end

  def edit
    @anonymous_user_plan = AnonymousUserPlan.find(params[:id])
    count = 10 - @anonymous_user_plan.destinations.count
    count.times { @anonymous_user_plan.destinations.build }
    gon.planData = @anonymous_user_plan.destinations.map{|d| d.name}
  end

  def update
    @anonymous_user_plan = AnonymousUserPlan.find(params[:id])
    if @anonymous_user_plan.update_attributes(plan_params)
      flash[:success] = "プランが更新されました"
      redirect_to edit_anonymous_user_plan_url
    else
      flash[:danger] = "タイトルを入力してください"
      redirect_to edit_anonymous_user_plan_url
    end
  end

  private
    def plan_params
      params.require(:anonymous_user_plan).permit(
        :title,
        :picture,
        :prefectures,
        destinations_attributes: [:id, :time, :name, :_destroy, :picture, :description]
      )
    end
end

app/helpers/anonymous_user_plans_helper.rb
module AnonymousUserPlansHelper
end

app/views/anonymous_user_plans/_anonymous_user_plan.html.erb
<li>
  <div id="plan-abst" class="plan-inline-block">
    <div id="plan-user" class="plan-inline-block">名無しさん</div>
    <div id="plan-posted-time">
      <%= time_ago_in_words(anonymous_user_plan.created_at) %>前
    </div>
    <br>
    <%= link_to anonymous_user_plan.title, anonymous_user_plan %>
    <div id="plan-location">
      <%=  anonymous_user_plan.prefectures %>
    </div>
  </div>
  <div id="planThumb" class="plan-inline-block">
    <% if anonymous_user_plan.picture? %>
      <%= image_tag anonymous_user_plan.picture.url(:planThumb) %>
    <% else %>
      <%= image_tag('no_image.png') %>
    <% end %>
  </div>
  <hr/>
</li>

app/views/anonymous_user_plans/_form.html.erb
<div id='mapContainer'>
  <div id='planList'>
    <%= form_for(@anonymous_user_plan, url: yield(:url) ) do |f| %>

      <%= f.label :タイトル %>
      <%= f.text_field :title, class: 'form-control' %>

      <div id="thumb_design">
        <p style="padding-top:15px; padding-right:20px; font-size:16px;">サムネイル画像を選択して下さい</p>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', id: "thumbnail", style: "display:none;" %>
        <img src="/thumbimg.png" id="img1" style="width:60px;height:60px; padding-top:10px;" onclick="$('#thumbnail').click();" />
      </div>
      <label>行程</label>
      <ol id="plan-ol" style="text-align: center;">
        <%= f.fields_for :destinations do |destinations_form| %>
          <button type="button" v-if="show_button[<%= destinations_form.index %>]" @click="display(<%= destinations_form.index %>)">{{button_message[<%= destinations_form.index %>]}}</button>
          <br v-if="show_button[<%= destinations_form.index %>]"/>
          <li class="plan-li" id="plan-li-<%= destinations_form.index %>" v-if="show_li[<%= destinations_form.index %>]">
            <div class='row'>
              <div class="col-4">
                <%= destinations_form.time_field :time, class: 'form-control' %>
              </div>

              <div class="col-5">
                <%= destinations_form.text_field :name, class: 'form-control' %>
              </div>

              <div class="view_box" style="display:flex;">
                <%= image_tag '/Fileicon.jpg',class: 'select_file_image',onClick: "$('#file#{destinations_form.index}').click()" %>
                <%= destinations_form.file_field :picture, style: 'display: none;',id:"file#{destinations_form.index}", class: 'form-control file', accept: 'image/jpeg,image/gif,image/png', "v-on:change"=>"preview(#{destinations_form.index})" %>
              </div>
            </div>
            <div class="row">
              <div class="col-12">
                <%= destinations_form.text_area :description, placeholder: "詳細を入力できます" %>
              </div>
            </div>
          </li>
        <% end %>
      </ol>
      <div class="center-button">
        <button type="button" onclick="updateMap('anonymous_user_plan')">地図に反映</button>
      </div>
  </div>
  <div id="item">
    <input id="address" type="textbox" placeholder="都道府県を入力してください">
    <input type="button" value="移動" onclick="codeAddress()">
    <div id="map" style="height: 650px;">
    </div>
    <span class="picture">
      <%= f.text_field :prefectures, id: "pref_names", style: "display:none;" %>
    </span>
    <input id="markerAddress" type="textbox" >
    <input type="button" value="追加" onclick="addMarker()">
  </div>
</div>
<%= f.button yield(:button_text),type:"button" ,onClick: "$('#cityName').click();" ,style: "width:100%;", class: "btn btn-primary" %>
<button type="button" onclick="getPreNames('anonymous_user_plan', '<%= yield(:action_name)%>')" style="display: none;" id="cityName"></button>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<%= javascript_include_tag 'image_preview.js' %>

app/views/anonymous_user_plans/edit.html.erb
<%= javascript_include_tag 'gmap.js' %>
<% provide(:button_text, 'プランを更新する') %>
<% provide(:url, anonymous_user_plan_path) %>
<% provide(:action_name, 'edit') %>
<h2>地図しおり</h2>

<%= render 'form' %>

<div id="planLink">
  <%= link_to "出来上がったプランを見る", @anonymous_user_plan %>
</div>

app/views/anonymous_user_plans/new.html.erb
<%= javascript_include_tag 'gmap.js' %>
<% provide(:title, 'プラン作成') %>
<% provide(:button_text, 'プランを作成する') %>
<% provide(:url, anonymous_user_planup_path) %>
<% provide(:action_name, 'new') %>

<h1>プラン作成</h1>

<%= render 'form' %>

app/views/anonymous_user_plans/show.html.erb
<%= javascript_include_tag 'gmap.js' %>
<div class="plan-info">
  <div class="plan-title">
    <h1>
      <%= @anonymous_user_plan.title %>
    </h1>
  </div>
  <div class="plan-user">
    <h3>名無しさん</h3>
  </div>
  <div>
    <% if @anonymous_user_plan.picture? %>
      <%= image_tag @anonymous_user_plan.picture.url %>
    <% else %>
      <%= image_tag('no_image.png') %>
    <% end %>
  </div>
</div>
<div id="link-wrapper">
  <div class="link-button" id="like-button">
    <a>いいね</a>
  </div>
  <div class="link-button" id="favorite-button">
    <a>お気に入り</a>
  </div>
  <div class="link-button" id="clone-button">
    <%= link_to "クローン", clone_path(id: @anonymous_user_plan.id, is_anonymous: true) %>
  </div>
</div>
<div id='plan-detail'>
  <% if @anonymous_user_plan.destinations.any? %>
    <ol class="destinations">
      <%= render @destinations %>
    </ol>
  <% end %>
</div>
<div id="map">
</div>

<style>
.container{
  padding:0px;
}
</style>