config/routes.rb
Rails.application.routes.draw do
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  get 'sitemap', to: redirect('http://s3-ap-northeast-1.amazonaws.com/'+ENV['S3_BUCKET']+'/sitemaps/sitemap.xml.gz')

  get 'plans/update'

  get 'images/ogp.png', to: 'images#ogp', as: 'images_ogp'

  get 'sessions/new'

  root 'static_pages#home'

  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/rule', to: 'static_pages#rule'
  get  '/privacy', to: 'static_pages#privacy'
  get  '/create', to: 'static_pages#create'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/search', to: 'users#search'
  get '/planup', to: 'plans#new'
  post '/planup', to: 'plans#create'
  get '/clone', to: 'plans#clone'
  post '/clone', to: 'plans#create'
  get '/anonymous_user_planup', to: 'anonymous_user_plans#new'
  post '/anonymous_user_planup', to: 'anonymous_user_plans#create'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :plans, only: [:index, :update, :show, :edit, :new, :create]
  resources :anonymous_user_plans
  resources :users do
    member do
      get :liking
    end
  end
  resources :plans do
    member do
      get :likers
    end
  end
  resources :likes, only: [:create, :destroy]
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :destinations, as: :placeable, dependent: :destroy, inverse_of: :placeable
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  accepts_nested_attributes_for :destinations, allow_destroy: true
  # , reject_if: :all_blank
  validates :title, presence: true
  validates :user_id, presence: true
  validate  :picture_size
  mount_uploader :picture, PictureUploader
  default_scope -> { order(created_at: :desc) }
  amoeba do
    enable
  end

  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :logged_in_user, only: [:create, :edit, :update, :new, :clone, :destroy]

  def index
    if params[:q]
      @q = Plan.ransack(params[:q])
      params[:p] = params[:q].deep_dup
      params[:p].delete(:user_name_or_title_or_destinations_description_or_destinations_name_or_prefectures_cont)
      params[:p][:title_or_destinations_description_or_destinations_name_or_prefectures_cont] = \
        params[:q][:user_name_or_title_or_destinations_description_or_destinations_name_or_prefectures_cont]
      @plans = @q.result(distinct: true).paginate(page: params[:page])
      @anonymous_q = AnonymousUserPlan.ransack(params[:p])
      @anonymousUserPlans = @anonymous_q.result(distinct: true)
    else
      @q = Plan.ransack(params[:q])
      @plans = Plan.where(published: true).paginate(page: params[:page])
      @anonymousUserPlans = AnonymousUserPlan.all
    end
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update_attributes(plan_params)
      flash[:success] = "プランが更新されました"
      redirect_to edit_plan_url
    else
      flash[:danger] = "タイトルを入力してください"
      redirect_to edit_plan_url
    end
  end

  def edit
    @plan = Plan.find(params[:id])
    gon.planData = @plan.destinations.map{|d| d.name}
    count = 10 - @plan.destinations.count
    count.times { @plan.destinations.build }
  end

  def show
    @plan = Plan.find(params[:id])
    @destinations = @plan.destinations
    gon.planData = @destinations.map{|d| d.name}
  end

  def create
    @plan = current_user.plans.build(plan_params)
    if @plan.save
      redirect_to controller: 'plans', action: 'show', id: @plan.id
    else
      flash[:danger] = "タイトルを入力してください"
      redirect_to acition: 'new'
    end
  end

  def new
    @plan = Plan.new
    10.times { @plan.destinations.build }
  end

  def clone
    if params[:is_anonymous]
      p = AnonymousUserPlan.find(params[:id]).amoeba_dup
      @plan = Plan.new(title:p.title, destinations: p.destinations)
      gon.planData = @plan.destinations.map{|d| d.name}
      count = 10 - @plan.destinations.count
      count.times { @plan.destinations.build }
    else
      @old_plan = Plan.find(params[:id])
      if current_user?(@old_plan.user)
        redirect_to edit_plan_url(@old_plan), flash:{id: @old_plan.id}
        flash.discard(:id)
      else
        p = Plan.find(params[:id]).amoeba_dup
        @plan = Plan.new(title:p.title, destinations: p.destinations)
        gon.planData = @plan.destinations.map{|d| d.name}
        count = 10 - @plan.destinations.count
        count.times { @plan.destinations.build }
      end
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @user = @plan.user
    if current_user?(@user)
      @plan.destroy
      flash[:success] = "プランを削除しました"
      redirect_to @user
    end
  end

  private
    def plan_params
      params.require(:plan).permit(
        :title,
        :picture,
        :user_id,
        :published,
        :prefectures,
        destinations_attributes: [:id, :time, :name, :_destroy, :picture, :description]
      )
    end

    def search_params
      params.require(:q).permit(:title_or_destinations_description_or_destinations_name_cont)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_before_login_like.html.erb
<%= link_to likes_path(plan_id: @plan.id), method: :post do %>
  <div id="like-icon">
    <i class="far fa-heart fa-2x"></i><br/>
    いいね
  </div>
<% end %>

<style>
  #like-icon{
    line-height:26px;
  }
</style>

app/views/plans/_form.html.erb
<div id='mapContainer'>
  <div id='planList'>
    <%= form_for(@plan, url: yield(:url) ) do |f| %>

      <%= f.label :タイトル %>
      <%= f.text_field :title, class: 'form-control' %>

      <div id="thumb_design">
        <p style="padding-top:15px; padding-right:20px; font-size:16px;">サムネイル画像を選択して下さい</p>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', id: "thumbnail", style: "display:none;" %>
        <img src="/thumbimg.png" id="img1" style="width:60px;height:60px; padding-top:10px;" onclick="$('#thumbnail').click();" />
      </div>
      <label>行程</label>
      <ol id="plan-ol" style="text-align: center;">
        <%= f.fields_for :destinations do |destinations_form| %>
          <button type="button" v-if="show_button[<%= destinations_form.index %>]" @click="display(<%= destinations_form.index %>)">{{button_message[<%= destinations_form.index %>]}}</button>
          <br v-if="show_button[<%= destinations_form.index %>]"/>
          <li class="plan-li" id="plan-li-<%= destinations_form.index %>" v-if="show_li[<%= destinations_form.index %>]">
            <div class='row'>
              <div class="col-4">
                <%= destinations_form.time_field :time, class: 'form-control' %>
              </div>

              <div class="col-5">
                <%= destinations_form.text_field :name, class: 'form-control' %>
              </div>

              <div class="view_box" style="display:flex;">
                <%= image_tag '/Fileicon.jpg',class: 'select_file_image',onClick: "$('#file#{destinations_form.index}').click()" %>
                <%= destinations_form.file_field :picture, style: 'display: none;',id:"file#{destinations_form.index}", class: 'form-control file', accept: 'image/jpeg,image/gif,image/png', "v-on:change"=>"preview(#{destinations_form.index})" %>
              </div>
            </div>
            <div class="row">
              <div class="col-12">
                <%= destinations_form.text_area :description, placeholder: "詳細を入力できます" %>
              </div>
            </div>
          </li>
        <% end %>
      </ol>
      <div class="center-button">
        <button type="button" onclick="updateMap('plan')">地図に反映</button>
      </div>
  </div>
  <div id="item">
    <input id="address" type="textbox" placeholder="都道府県を入力してください">
    <input type="button" value="移動" onclick="codeAddress()">
    <div id="map" style="height: 650px;">
    </div>
    <span class="picture">
      <%= f.text_field :prefectures, id: "pref_names", style: "display:none;" %>
    </span>
    <div class="publish-buttons">
      <label><%= f.radio_button :published, true %>公開する</label>
      <label><%= f.radio_button :published, false %>非公開にする</label>
    </div>
    <input id="markerAddress" type="textbox" >
    <input type="button" value="追加" onclick="addMarker()">
  </div>
</div>
<%= f.button yield(:button_text),type:"button" ,onClick: "$('#cityName').click();" ,style: "width:100%;", class: "btn btn-primary" %>
<button type="button" onclick="getPreNames('plan' , '<%= yield(:action_name)%>')" style="display: none;" id="cityName"></button>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<%= javascript_include_tag 'image_preview.js' %>

app/views/plans/_like.html.erb
<%= link_to likes_path(plan_id: @plan.id), method: :post, remote: true  do %>
  <div id="like-icon">
    <i class="far fa-heart fa-2x"></i><br/>
    いいね
  </div>
<% end %>

<style>
  #like-icon{
    line-height:26px;
  }
</style>

app/views/plans/_like_button.html.erb
<div class="link-button" id="like-button">
  <% if current_user %>
    <% if current_user.liking?(@plan) %>
      <%= render 'unlike' %>
    <% else %>
      <%= render 'like' %>
    <% end %>
  <% else %>
    <%= render 'before_login_like'%>
  <% end %>
</div>

<style>
#like-icon{
  line-height:26px;
}
</style>

app/views/plans/_plan.html.erb
<li>
  <div id="plan-abst" class="plan-inline-block">
    <div id="plan-user" class="plan-inline-block"><%= link_to plan.user.name, plan.user %></div>
    <div id="plan-posted-time">
      <%= time_ago_in_words(plan.created_at) %>前
    </div>
    <br>
    <%= link_to plan.title, plan, class:"plan-index-title" %>
    <div id="plan-location">
      <%= plan.prefectures %>
    </div>
  </div>
  <div id="planThumb" class="plan-inline-block">
    <% if plan.picture? %>
      <%= image_tag plan.picture.url(:planThumb) %>
    <% else %>
      <%= image_tag('no_image.png') %>
    <% end %>
    <% if controller.controller_name == 'users' && current_user?(plan.user) %>
      <%= link_to "削除", plan, method: :delete, data: { confirm: "本当に削除しますか？" } %>
    <% end %>
  </div>
  <hr/>
</li>

app/views/plans/_unlike.html.erb
<%= link_to like_path(@plan.id), method: :delete, remote: true  do %>
  <div id="unlike-icon">
    <i class="fa fa-heart fa-2x"></i><br/>
    いいね消去
  </div>
<% end %>

<style>
  #unlike-icon{
    line-height:26px;
  }
</style>

app/views/plans/clone.html.erb
<%= javascript_include_tag 'gmap.js' %>
<% provide(:title, 'プラン複製') %>
<% provide(:button_text, 'プランを複製する') %>
<% provide(:url, clone_path) %>

<h1>プラン複製</h1>

<%= render 'form' %>

app/views/plans/create.html.erb
<h1>Plans#create</h1>
<p>Find me in app/views/plans/create.html.erb</p>

app/views/plans/edit.html.erb
<%= javascript_include_tag 'gmap.js' %>
<% provide(:title, 'プラン編集') %>
<% provide(:button_text, 'プランを更新する') %>
<% provide(:url, plan_path) %>
<% provide(:action_name, 'edit') %>

<h2>地図しおり</h2>

<%= render 'form' %>

<div id="planLink">
  <%= link_to "出来上がったプランを見る", @plan %>
</div>

app/views/plans/index.html.erb
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

<% provide(:title, 'All plans') %>
<h1>旅メモ</h1>
<%= search_form_for @q, url: plans_path do |f| %>
  <dl>
    <dt><%= f.label :user_name_or_title_or_destinations_description_or_destinations_name_cont, "キーワード" %></dt>
    <dd><%= f.search_field :user_name_or_title_or_destinations_description_or_destinations_name_or_prefectures_cont %></dd>
  </dl>
  <%= f.submit class: 'search-q-btn' %>
<% end %>
<div id="trip-memos">
  <ul class="tabs">
    <li @click="changeMemos(1)">登録済みユーザー</li>
    <li @click="changeMemos(0)">未登録ユーザー</li>
  </ul>
  <div id="named-user-memos" v-if="named">
    <%= will_paginate %>
    <ul class="plans">
      <%= render @plans %>
    </ul>
    <%= will_paginate %>
  </div>
  <div id="anonymous-user-memos" v-if="anonymous">
    <ul class="plans">
      <%= render @anonymousUserPlans %>
    </ul>
  </div>
</div>

<%= javascript_include_tag 'plan.js' %>

app/views/plans/new.html.erb
<%= javascript_include_tag 'gmap.js' %>
<% provide(:title, 'プラン作成') %>
<% provide(:button_text, 'プランを作成する') %>
<% provide(:url, planup_path) %>
<% provide(:action_name, 'new') %>

<h1>プラン作成</h1>

<%= render 'form' %>

app/views/plans/show.html.erb
<%= javascript_include_tag 'gmap.js' %>
<div class="plan-info">
  <div class="plan-title">
    <h1>
      <%= @plan.title %>
    </h1>
  </div>
  <div class="plan-user">
    <%= link_to @plan.user.name, @plan.user %>
  </div>
  <div>
    <% if @plan.picture? %>
      <%= image_tag @plan.picture.url %>
    <% else %>
      <%= image_tag('no_image.png') %>
    <% end %>
  </div>
</div>
<div id="link-wrapper">
  <%= render 'like_button' %>
  <div class="link-button" id="favorite-button">
    <a>お気に入り</a>
  </div>
  <div class="link-button" id="clone-button">
    <% if current_user?(@plan.user) %>
      <%= link_to "編集", edit_plan_path %>
    <% else %>
      <%= link_to "クローン", clone_path(id: @plan.id) %>
    <% end %>
  </div>
</div>
<div id='plan-detail'>
  <% if @plan.destinations.any? %>
    <ol class="destinations">
      <%= render @destinations %>
    </ol>
  <% end %>
</div>
<div id="map">
</div>

<style>
.container{
  padding:0px;
}
</style>

app/views/plans/show_like.html.erb
<% provide(:title, @title) %>
<div>
  <h1><%= @title %></h1>
  <% if @plans.any? %>
    <ul class="plans">
      <%= render @plans %>
    </ul>
  <% end %>
</div>

app/views/plans/update.html.erb
<h1>Plans#update</h1>
<p>Find me in app/views/plans/update.html.erb</p>