config/routes.rb
Rails.application.routes.draw do
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  get 'sitemap', to: redirect('http://s3-ap-northeast-1.amazonaws.com/'+ENV['S3_BUCKET']+'/sitemaps/sitemap.xml.gz')

  get 'plans/update'

  get 'images/ogp.png', to: 'images#ogp', as: 'images_ogp'

  get 'sessions/new'

  root 'static_pages#home'

  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/rule', to: 'static_pages#rule'
  get  '/privacy', to: 'static_pages#privacy'
  get  '/create', to: 'static_pages#create'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/search', to: 'users#search'
  get '/planup', to: 'plans#new'
  post '/planup', to: 'plans#create'
  get '/clone', to: 'plans#clone'
  post '/clone', to: 'plans#create'
  get '/anonymous_user_planup', to: 'anonymous_user_plans#new'
  post '/anonymous_user_planup', to: 'anonymous_user_plans#create'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :plans, only: [:index, :update, :show, :edit, :new, :create]
  resources :anonymous_user_plans
  resources :users do
    member do
      get :liking
    end
  end
  resources :plans do
    member do
      get :likers
    end
  end
  resources :likes, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © 2019 Memorip
  </small>
  <nav>
    <ul>
      <li><%= link_to "ホーム",   root_path %></li>
      <li><%= link_to "Memoripとは",   about_path %></li>
      <li><%= link_to "利用規約", rule_path %></li>
      <li><%= link_to "プライバシーポリシー", privacy_path %></li>
      <li><%= link_to "お問い合わせ・ご意見・ご要望", inquiry_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="drawer-navbar" role="banner" id="header_layout">
  <div class="drawer-container">
    <div class="drawer-navbar-header">
      <%= link_to "Memorip", root_path, id: "logo", class:"drawer-brand" %>
      <button type="button" class="drawer-toggle drawer-hamburger">
        <span class="sr-only">toggle navigation</span>
        <span class="drawer-hamburger-icon"></span>
      </button>
    </div>
    <nav class="drawer-nav" role="navigation">
      <ul class="drawer-menu drawer-menu--right">
        <li class="nav-item drawer-menu-item"><%= link_to "ホーム",   root_path , class: "nav-link" %></li>
        <!-- <li class="nav-item"><%= link_to "Help",   help_path , class: "nav-link" %></li> -->
        <li class="nav-item drawer-menu-item"><%= link_to "プラン一覧", "/plans", class: "nav-link"%></li>
        <% if logged_in? %>
          <li class="nav-item drawer-menu-item"><%= link_to "プラン作成", planup_path, class: "nav-link"%></li>
        <% else %>
          <li class="nav-item drawer-menu-item"><%= link_to "プラン作成", create_path, class: "nav-link"%></li>
        <% end %>
        <% if logged_in? %>
          <li class="dropdown nav-item drawer-menu-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <div class="dropdown-menu dropdown-menu-left">
              <%= link_to "マイページ", current_user, class: "dropdown-item" %>
              <%= link_to "プロフィール設定", edit_user_path(current_user), class: "dropdown-item"%>
              <div class="dropdown-divider"></div>
              <%= link_to "ログアウト", logout_path, method: :delete, class: "dropdown-item"%>
            </div>
          </li>
        <% else %>
          <li class="drawer-menu-item"><%= link_to "ログイン", login_path , class: "nav-link" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<script>
  $(document).ready(function() {
    $('.drawer').drawer();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memorip</title>
    <%= csrf_meta_tags %>
    <%= include_gon(:init => true) %>
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload', :debug => true %>
    <% self_css_path = "/assets/"+controller.controller_name  %>
    <%= stylesheet_link_tag self_css_path, :media => "all" %>
    <%= stylesheet_link_tag "drawer.min.css", :media => "all" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' , :debug => true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'%>
    <meta name="google-site-verification" content="po8157oyj1IXaaMxeAi_p5sJOJ9TJtPqYZAIHN800pQ" />
    <meta name="viewport" content="width=device-width">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.2.0/iscroll.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/js/drawer.min.js"></script>
    <script src=<%=ENV['GOOGLE_MAP_URL']%> async defer></script>
    <script src="https://kit.fontawesome.com/81a1ab3943.js" crossorigin="anonymous"></script>
  </head>

  <body class="drawer drawer--right drawer--navbarTopGutter">
    <%= render 'layouts/header' %>
    <div class="container" style="margin-top:40px; margin-bottom:40px">
      <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>